### ISSUE TITLE
source data error

### ISSUE THREAD

**Issue by 3vivekb** [aakashhdesai/sj-data-analysis#1]
sj_economics_monthly_2006_2016.csv vs 
sj = pd.read_csv("sj_economics_monthly.csv")

**Comment by 3vivekb** [comment]
Also - where does this data come from?

**Comment by aakashhdesai** [comment]
@3vivekb http://data.sanjoseca.gov/home - various data exports from there, but have been appending this one spreadsheet from the ones that have a key of monthly time between 2006-2016.
